name = "RDKafka"
uuid = "43e2f499-f4c7-585f-8317-cbc2d9c3bf8f"
authors = ["Andrei Zhabinski <andrei.zhabinski@gmail.com>"]
version = "0.1.0"

[deps]
librdkafka_jll = "7943bfb0-7437-5acd-a008-22777931c7aa"

[compat]
julia = "1.3"
librdkafka_jll = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
